test = {   'name': 'q8',
    'points': None,
    'suites': [   {   'cases': [   {   'code': '>>> # Make sure your formula for predicted_distance_m\n>>> # is correct\n>>> predicted_distance_m == 1.1702236946593048\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> difference == 0.040223694659304865\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
